COUNTRY_CODES = {
    "UZ": ("🇺🇿", "O'zbekiston"),
    "RU": ("🇷🇺", "Rossiya"),
    "US": ("🇺🇸", "Amerika Qo'shma Shtatlari"),
    "GB": ("🇬🇧", "Buyuk Britaniya"),
    "DE": ("🇩🇪", "Germaniya"),
    "FR": ("🇫🇷", "Fransiya"),
    "IT": ("🇮🇹", "Italiya"),
    "ES": ("🇪🇸", "Ispaniya"),
    "CN": ("🇨🇳", "Xitoy"),
    "JP": ("🇯🇵", "Yaponiya"),
    "KR": ("🇰🇷", "Janubiy Koreya"),
    "KZ": ("🇰🇿", "Qozog'iston"),
    "KG": ("🇰🇬", "Qirg'iziston"),
    "TJ": ("🇹🇯", "Tojikiston"),
    "TM": ("🇹🇲", "Turkmaniston"),
    "AE": ("🇦🇪", "Birlashgan Arab Amirliklari"),
    "TR": ("🇹🇷", "Turkiya"),
    "IN": ("🇮🇳", "Hindiston"),
    "CA": ("🇨🇦", "Kanada"),
    "AU": ("🇦🇺", "Avstraliya"),
    "BR": ("🇧🇷", "Braziliya"),
    "UA": ("🇺🇦", "Ukraina"),
    "PL": ("🇵🇱", "Polsha"),
    "NL": ("🇳🇱", "Niderlandiya"),
    "SE": ("🇸🇪", "Shvetsiya"),
    "CH": ("🇨🇭", "Shveytsariya"),
    "NO": ("🇳🇴", "Norvegiya"),
    "FI": ("🇫🇮", "Finlandiya"),
    "AF": ("🇦🇫", "Afg'oniston"),
    "AM": ("🇦🇲", "Armaniston"),
    "AZ": ("🇦🇿", "Ozarbayjon"),
    "GE": ("🇬🇪", "Gruziya"),
    "GR": ("🇬🇷", "Gretsiya"),
    "HU": ("🇭🇺", "Vengriya"),
    "ID": ("🇮🇩", "Indoneziya"),
    "IL": ("🇮🇱", "Isroil"),
    "IQ": ("🇮🇶", "Iroq"),
    "IR": ("🇮🇷", "Eron"),
    "MX": ("🇲🇽", "Meksika"),
    "MY": ("🇲🇾", "Malayziya"),
    "NG": ("🇳🇬", "Nigeriya"),
    "PK": ("🇵🇰", "Pokiston"),
    "PT": ("🇵🇹", "Portugaliya"),
    "RO": ("🇷🇴", "Ruminiya"),
    "SA": ("🇸🇦", "Saudiya Arabistoni"),
    "SG": ("🇸🇬", "Singapur"),
    "TH": ("🇹🇭", "Tailand"),
    "VN": ("🇻🇳", "Vyetnam"),
    "ZA": ("🇿🇦", "Janubiy Afrika"),
    "EG": ("🇪🇬", "Misr"),
    "AT": ("🇦🇹", "Avstriya"),
    "BE": ("🇧🇪", "Belgiya"),
    "CZ": ("🇨🇿", "Chexiya"),
    "DK": ("🇩🇰", "Daniya"),
    "SK": ("🇸🇰", "Slovakiya"),
    "RS": ("🇷🇸", "Serbiya"),
    "HR": ("🇭🇷", "Xorvatiya"),
    "BG": ("🇧🇬", "Bolgariya"),
    "LT": ("🇱🇹", "Litva"),
    "LV": ("🇱🇻", "Latviya"),
    "EE": ("🇪🇪", "Estoniya"),
    "BY": ("🇧🇾", "Belarus"),
    "MD": ("🇲🇩", "Moldova"),
    "MN": ("🇲🇳", "Mo'g'uliston"),
    "NZ": ("🇳🇿", "Yangi Zelandiya"),
    "PH": ("🇵🇭", "Filippin"),
    "AR": ("🇦🇷", "Argentina"),
    "CL": ("🇨🇱", "Chili"),
    "CO": ("🇨🇴", "Kolumbiya"),
    "KW": ("🇰🇼", "Quvayt"),
    "QA": ("🇶🇦", "Qatar"),
    "OM": ("🇴🇲", "Ummon"),
    "JO": ("🇯🇴", "Iordaniya"),
    "LB": ("🇱🇧", "Livan"),
    "SY": ("🇸🇾", "Suriya"),
    "MA": ("🇲🇦", "Marokash"),
    "TN": ("🇹🇳", "Tunis"),
    "DZ": ("🇩🇿", "Jazoir"),
    "ET": ("🇪🇹", "Efiopiya"),
    "KE": ("🇰🇪", "Keniya"),
    "GH": ("🇬🇭", "Gana"),
    "TZ": ("🇹🇿", "Tanzaniya"),
}
